### ISSUE TITLE
静默通知字段名不正确

### ISSUE THREAD

**Issue by lcj0304** [ylywyn/jpush-api-go-client#2]
现在：发送ios静默通知时，会收不到。
原因：
type IOSNotice struct {
    Alert            string                 `json:"alert"`
    Sound            string                 `json:"sound,omitempty"`
    Badge            int                    `json:"badge,omitempty"`
    ContentAvailable bool                   `json:"Content-available,omitempty"`
    Category         string                 `json:"category,omitempty"`
    Extras           map[string]interface{} `json:"extras,omitempty"`
}

ContentAvailable  字段的tag  第一个字母改为小写才正确。

**Comment by ylywyn** [comment]
是的，多谢
