### ISSUE TITLE
badge +1

### ISSUE THREAD

**Issue by com314159** [ylywyn/jpush-api-go-client#3]
你好, 看到jpush文档可以实现badge+1的功能, 这份SDK请问如何实现呢? 因为Badge是int类型, 如果是string类型我直接指定"+1"字符串就好, int是无法指定+1的

**Comment by hanbge** [comment]
agree

**Comment by ghost** [comment]
same problem

**Comment by ylywyn** [comment]
抱歉，很久不弄这个了，没测试环境了。
